# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/react-native/scripts/react_native_pods' 
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'


target 'Uber_fms_2021' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uber_fms_2021

  target 'Uber_fms_2021Tests' do
    inherit! :search_paths
    # Pods for testing
  
  
  end

end

